workflows:
  android:
    name: Build Android App
    environment:
      flutter: 3.19.0
    scripts:
      - name: Flutter Build
        script: |
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
