name: water_village_bill
description: แอปประปาหมู่บ้าน
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.1
  cloud_firestore: ^4.13.6
  intl: ^0.18.1
  mobile_scanner: ^3.5.5
  image_picker: ^1.0.7
  pdf: ^3.10.7
  path_provider: ^2.1.2
  excel: ^2.1.0
  http: ^1.1.2

flutter:
  uses-material-design: true
